# helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
# helm install -n tracing -f values.yaml jaeger jaegertracing/jaeger

# https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger#all-in-one-in-memory-configuration
provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
storage:
  type: memory
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false